### ISSUE TITLE
Nse upload data late in old websight

### ISSUE THREAD

**Issue by jain203** [virresh/StockD#16]
hi virresh, from few days nse upload bhavcopy late on old  web-sight . (may be they are going to shut it down in near future. )because  of that your downloader did not download bhavcopy on time. it is possible to shift to new web-sight.

**Comment by virresh** [comment]
Hi @jain203 
StockD supports both new website and old website from the beginning

Please try using Nse Daily or Nse Daily (with Delivery) link profile
Both of them use new website as data source

More information on link profiles:
https://github.com/virresh/StockD/wiki/User-Guide#what-are-link-profiles


Please let me know the results and any pending problems if they remain.

**Comment by virresh** [comment]
Closing this issue. Feel free to reopen or create a new one if you feel it doesn't work for you.
