### ISSUE TITLE
Delivery Data

### ISSUE THREAD

**Issue by kbloganathan** [virresh/StockD#18]
Delivery Data not downloading for Nse Equity and Indices. Please check and fix the bug.

**Comment by virresh** [comment]
@kbloganathan thanks for reporting.

Can you confirm which all link profiles are in error?
There are four as of now: https://github.com/virresh/StockD/wiki/User-Guide#what-are-link-profiles

**Comment by virresh** [comment]
Closing issue as not reproducible.
