### ISSUE TITLE
WHICH Stock Series  Data is going in Final Converted File ?

### ISSUE THREAD

**Issue by tgbssk** [virresh/StockD#24]
(1) WHICH Stock Series  Data is going in Final Converted File ?
Currently NSE Cash Market data has 3 Duplicate Symbols. You can Check . SHAREINDIA, RADIOCITY, AARTISURF
https://nsearchives.nseindia.com/products/content/sec_bhavdata_full_02082024.csv
OR
https://nsearchives.nseindia.com/content/cm/BhavCopy_NSE_CM_0_0_0_20240802_F_0000.csv.zip
OR
![image_2024-08-05_084833097](https://github.com/user-attachments/assets/d29fc774-8502-4748-97bd-7a0bcd7d4ad4)
https://nsearchives.nseindia.com/archives/equities/bhavcopy/pr/PR020824.zip   Check Readme in Zipfile.  In this zip Pdddmmyy.csv e prddmmyy.csv  may be useful.

Prddmmyy.csv file contains security wise market data information along with the Index details.
(2)
NSE has made Big complications in new data Format
https://nsearchives.nseindia.com/products/content/sec_bhavdata_full_17072024.csv (Holiday But Data Comes )
https://nsearchives.nseindia.com/products/content/sec_bhavdata_full_28072024.csv (Sunday But Data Comes )
These links have also given data for Sunday and Holiday But Good part is that on holiday it gives data of previous working day
and on Sunday it gives data of Friday so even if those extra files are downloaded it has data of working day in it name may have other date.
-Regards

**Comment by virresh** [comment]
> WHICH Stock Series Data is going in Final Converted File ?

'EQ' and 'BE'

> Currently NSE Cash Market data has 3 Duplicate Symbols. You can Check . SHAREINDIA, RADIOCITY, AARTISURF

I've checked all three files you linked to, and don't see any duplicates. 
Exact links of which files are used is present in the link profile link. See the user guide for details.

> Holiday But Data Comes 

and
> Sunday But Data Comes

StockD already handles these cases. It will not download data if date within file and url do not match. Not sure what you want to convey here.

**Comment by virresh** [comment]
NSE has explained the series concept here - https://www.nseindia.com/market-data/legend-of-series
in case there is any confusion about why only EQ and BE is used for equity EOD data.

**Comment by tgbssk** [comment]
Ok. ThanX for quick reply
I will read document about BE EQ but I have noticed that Only BE EQ series data is used mostly.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tgbssk** [comment]
>>> Not sure what you want to convey here.>>

I wanted to know what if duplicate symbols comes in ?
The data has duplicate symbols and that is in original NSE DATA
The issue is that when duplicate symbol comes second time that has flag other then EQ then a software like Amibroker just keeps track of Symbol Name and not Series Flag and then second symbol's values are imported and overwritten. 
Earlier some where in 2014 there was similar issue about Lupin now SHAREINDIA, RADIOCITY, AARTISURF are not much popular stocks. But Just take note that NSE has habit to change series flags and and add duplicate symbols. 
![image_2024-08-06_064939420](https://github.com/user-attachments/assets/03c0ee17-f8e7-4741-8dc0-7da2184c98b2)

**Comment by virresh** [comment]
Same symbol with a different series is not duplicate. It's a different entry and StockD will ignore extras other than BE and EQ series (fully executed trades)

In the picture you shared, output by stockd will only contain data from row 1835. Row 1836 will be ignored as it's data for non convertible preferential shares, not regular equity.

**Comment by tgbssk** [comment]
I know that but see what is conditions for amibroker's data import.

**Comment by virresh** [comment]
Sorry I don't understand the problem that you're having?

I don't think Amibroker cares about what series data you feed it, to my knowledge it's a charting software.

If you are unable to use output from StockD as input to your charting software, try asking Amibroker support. They might be able to help.

If you've noticed inconsistency in the output from StockD, i.e prices of some securities are incorrect, then kindly share the exact example with your expected output.

**Comment by tgbssk** [comment]
Thanx Once Again for quick reply.
StockD has No Problem Now. 
For me StockD is Good Enough ! Only issue that  it is bulky, but once application starts it is good. I download data on weekends, so downloading 5-6 files  and processing them is not a big issue. 
.
I will try to make something in C which will be single executable, without any extra dependencies  and fast. 
But it is  slow development work from my side. I'll let you know once is it done. Currently Downloader within date range
 is completed. But Exchange wise selective download,  conversion and direct import in Amibroker EOD Database with OLE is yet to be finished. It is just for my own interest , nothing but in the category of "One more thing done !"
Since You have said in StockD Data is only for BE EQ Series Stocks there will not be any issue of duplicate names with other series. 
.

Regards
![image_2024-08-07_094146990](https://github.com/user-attachments/assets/ede125b5-b9aa-4211-aada-c78a322cd13c)

**Comment by virresh** [comment]
Nice
